# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sm6375-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter oscar,$(TARGET_DEVICE)),)

endif
